const test=require("node:test"),assert=require("node:assert/strict"),M=require("../Model.js")
// RTM: REQ-FB-004, REQ-FB-008
const now=1700000000000
test("parse rejects malformed local ledgers",()=>{assert.deepEqual(M.parse("bad",now),[]);assert.deepEqual(M.parse(null,now),[]);assert.deepEqual(M.parse("null",now),[]);assert.deepEqual(M.parse(JSON.stringify({events:{}}),now),[])})
test("parse accepts only timestamped arrive and leave events",()=>{const r=M.parse(JSON.stringify({events:[{kind:"arrive",at:1699999940},{kind:"bad",at:1},{kind:"leave",at:1699992800}]}),now);assert.deepEqual(r,[{kind:"arrive",age:"1M"},{kind:"leave",age:"2H"}])})
test("parse covers event and clock edge cases",()=>{const r=M.parse(JSON.stringify({events:[null,{kind:"arrive",at:1700000010},{kind:"leave",at:1699999990},{kind:"arrive",at:"bad"},{kind:"arrive",at:0}]}),now);assert.deepEqual(r,[{kind:"arrive",age:"NOW"},{kind:"leave",age:"NOW"}]);assert.deepEqual(M.parse(JSON.stringify({events:[{kind:"leave",at:1699996400}]}),now),[{kind:"leave",age:"1H"}]);assert.equal(M.tooltipText([{kind:"arrive"}]),"Last boundary: arrive")})
test("parse bounds hostile ledgers and labels both states",()=>{const r=M.parse(JSON.stringify({events:Array.from({length:100},()=>({kind:"arrive",at:1}))}),now);assert.equal(r.length,M.MAX_EVENTS);assert.equal(M.pillText([]),"FLOW");assert.equal(M.pillText([{kind:"arrive"}]),"FLOW");assert.equal(M.pillText([{kind:"leave"}]),"PAUSE");assert.match(M.tooltipText([]),/intentional/)})
test("event kinds drive distinct accessible labels and theme-derived hues",()=>{assert.equal(M.kindLabel("arrive"),"CONTEXT OPENED");assert.equal(M.kindLabel("leave"),"CONTEXT CLOSED");assert.equal(M.kindHue("arrive"),0.43);assert.equal(M.kindHue("leave"),0.075)})
test("appendEvent keeps only valid bounded inline settings",()=>{let raw="[]";for(let i=0;i<40;i++)raw=M.appendEvent(raw,i%2?"leave":"arrive",now+i*1000);const events=JSON.parse(raw);assert.equal(events.length,M.MAX_EVENTS);assert.equal(events.at(-1).kind,"leave");assert.equal(M.appendEvent(raw,"bad",now),raw)})
test("appendEvent rejects invalid clocks and records seconds, not milliseconds",()=>{assert.deepEqual(JSON.parse(M.appendEvent("[]","arrive",1000)),[{kind:"arrive",at:1}]);assert.equal(M.appendEvent("[]","arrive",0),"[]");assert.equal(M.appendEvent("[]","arrive",Number.NaN),"[]");assert.equal(M.appendEvent("[]","arrive",Number.POSITIVE_INFINITY),"[]")})
test("inline settings parsing is byte bounded before JSON.parse",()=>{const event='[{"kind":"arrive","at":1}]';const exact=event+" ".repeat(M.MAX_STORED_BYTES-event.length);assert.deepEqual(M.storedEvents(exact),[{kind:"arrive",at:1}]);assert.deepEqual(M.storedEvents(exact+" "),[]);assert.deepEqual(M.storedEvents(null),[]);assert.deepEqual(M.parse("["+" ".repeat(M.MAX_STORED_BYTES)+"]",now),[])})
